name: mtail
adopt-info: mtail
summary: extract metrics from application logs
description: 'mtail is a tool for extracting metrics from application logs to be
  exported into a timeseries database or timeseries calculator for alerting and
  dashboarding.

  '
confinement: strict
grade: stable

apps:
  mtail:
    command: bin/mtail.wrapper
    daemon: simple
    plugs:
    - network-bind
    - log-observe
    - home

parts:

  ## This wrapper will be called to start mtail. It will import the default
  ## config file if none exists, and start mtail.
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      scripts/mtail.snap_wrapper: bin/mtail.wrapper
    stage:
      - etc
      - bin

  mtail:
    plugin: nil
    build-snaps: [go]
    build-packages: [make]
    override-build: |
      cd ..
      export GOPATH=$(pwd)/go
      mkdir -p $GOPATH/src
      go get -d github.com/google/mtail || /bin/true
      cd $GOPATH/src/github.com/google/mtail
      tag="$(git tag -l | sort -rV | head -n 1)"
      version="$(echo $tag | cut -d 'v' -f 2)"
      snapcraftctl set-version "$version"
      git checkout tags/$tag
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -p mtail $SNAPCRAFT_PART_INSTALL/bin/
